[[main]]
  name = "Check-In"
  url = "/check-in/"
  weight = 10

[[main]]
  name = "Schedule"
  url = "/schedule/"
  weight = 20

[[main]]
  name = "Invite"
  url = "/invite/"
  weight = 30

[[main]]
  name = "Conditions"
  url = "/conditions/"
  weight = 40

