[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "At the Park"
  url = "/now/"
  weight = 20

[[main]]
  name = "Who's going"
  url = "/ontheway/"
  weight = 30

[[main]]
  name = "Let's Meet"
  url = "/meet/"
  weight = 40

[[main]]
  name = "Park Conditions"
  url = "/conditions/"
  weight = 45

[[main]]
  name = "<img src=\"/icons/mail.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/contact/"
  weight = 50
