[[main]]
  name = "At the Park"
  url = "/at-the-park/"
  weight = 10

[[main]]
  name = "Schedule"
  url = "/schedule/"
  weight = 20

[[main]]
  name = "Invite"
  url = "/invite/"
  weight = 30

[[main]]
  name = "Conditions"
  url = "/conditions/"
  weight = 40

